version: '3.8'

services:
  server:
    build: .
    container_name: api-server
    command: node index.js
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: email-worker
    command: node workers/emailWorker.js
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
